In [34]:
import numpy as np

In [35]:
a=np.array([1,2,3,4,5,6,7,8])

In [36]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a[0]

np.int64(1)

In [38]:
zero=np.zeros(2)

In [39]:
zero

array([0., 0.])

In [43]:
ones=np.ones([4,4])

In [44]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
b=np.linspace(2,10,20)

In [46]:
b

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [50]:
b

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [51]:
c=np.linspace(1,10,20)

In [52]:
c

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [54]:
b+c

array([ 3.        ,  3.89473684,  4.78947368,  5.68421053,  6.57894737,
        7.47368421,  8.36842105,  9.26315789, 10.15789474, 11.05263158,
       11.94736842, 12.84210526, 13.73684211, 14.63157895, 15.52631579,
       16.42105263, 17.31578947, 18.21052632, 19.10526316, 20.        ])

In [55]:
b-c

array([1.        , 0.94736842, 0.89473684, 0.84210526, 0.78947368,
       0.73684211, 0.68421053, 0.63157895, 0.57894737, 0.52631579,
       0.47368421, 0.42105263, 0.36842105, 0.31578947, 0.26315789,
       0.21052632, 0.15789474, 0.10526316, 0.05263158, 0.        ])

In [56]:
b.shape

(20,)

In [59]:
bb=b.reshape(5,4)

In [60]:
bb

array([[ 2.        ,  2.42105263,  2.84210526,  3.26315789],
       [ 3.68421053,  4.10526316,  4.52631579,  4.94736842],
       [ 5.36842105,  5.78947368,  6.21052632,  6.63157895],
       [ 7.05263158,  7.47368421,  7.89473684,  8.31578947],
       [ 8.73684211,  9.15789474,  9.57894737, 10.        ]])

In [61]:
cc=c.reshape(5,4)
cc

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [62]:
ccc=cc.flatten()


In [63]:
ccc.shape

(20,)

In [64]:
np.square(ccc)

array([  1.        ,   2.17174515,   3.79224377,   5.86149584,
         8.37950139,  11.34626039,  14.76177285,  18.62603878,
        22.93905817,  27.70083102,  32.91135734,  38.57063712,
        44.67867036,  51.23545706,  58.24099723,  65.69529086,
        73.59833795,  81.9501385 ,  90.75069252, 100.        ])

In [65]:
np.save('d1',ccc)

In [66]:
np.load('d1.npy')

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])